# mod class
# 9-20-14
# Data Structures
# Princeton Ferro

CXX=g++
CXXFLAGS=-g -O0
BIN=mod

all: main.cpp Mod.cpp Mod.h
	$(CXX) $(CXXFLAGS) main.cpp Mod.cpp -o $(BIN)

.PHONY: clean
clean:
	$(RM) $(BIN)
