# deque - Makefile
CXX=g++
CXXFLAGS=-std=c++11

all: deque.h deque_main.cpp
	$(CXX) $(CXXFLAGS) deque_main.cpp -o dequemain

anti_deques: deque.h anti_deques.cpp
	$(CXX) $(CXXFLAGS) anti_deques.cpp -o antideques
